### ISSUE TITLE
Error when running the code

### ISSUE THREAD

**Issue by baharefatemi** [Maysir/GRCN#1]
Hello,

I followed all the instructions in the readme but when running the GRCN model for Cora in the fixed setup, I get the following error. It sounds like the error is coming from the fact that some package versions are not correct. Can you please help with this? 

>import torch_scatter.scatter_cuda
ModuleNotFoundError: No module named 'torch_scatter.scatter_cuda'

**Comment by PlusRoss** [comment]
Hi,

Thanks for raising this question. I think this should be related to the installation of [pytorch-geometric](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html). Did you follow its instruction especially this part:
![image](https://user-images.githubusercontent.com/21238425/85174771-020abd80-b244-11ea-8a7d-35a4662d8e5d.png)

**Comment by baharefatemi** [comment]
Thanks for getting back to me. At the first point, it did not work and I had to install another version of PyTorch than what you specified in the requirements and then uninstall and install torch-scatter again and it did work. I confirm that I reproduce your results. Thanks!

**Comment by PlusRoss** [comment]
Great to hear that! I noticed that my original pytorch version is too old to be compatible with the current pytorch-geometric package. I'll update the readme file soon.

**Comment by wanzhixiao** [comment]
The reported Acc of Cora dataset is on validation dataset or test data?,why the test Acc is 79.20%?
2021-06-01 16:26:34,020 Classification Val Acc: 82.20%
2021-06-01 16:26:34,021 Classification Test Acc: 79.20%

**Comment by PlusRoss** [comment]
The reported Acc is on test data. Is the shown validation acc the best validation acc over all the epochs?
